# Generated by Django 2.2 on 2019-05-19 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posY', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posZ', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelY', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelZ', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='api.Device')),
            ],
        ),
    ]
