# Generated by Django 2.2 on 2019-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posY', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posZ', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelY', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acelZ', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
